//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::data::Entity as Data;
pub use super::jobs::Entity as Jobs;
pub use super::projects::Entity as Projects;
pub use super::skills::Entity as Skills;
pub use super::users::Entity as Users;
